spring.application.name=spring-security

spring.security.user.name=nabeel
spring.security.user.password=1234

server.servlet.session.cookie.same-site=strict

spring.datasource.url=jdbc:postgresql://localhost:5432/db_jobapp
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver
